import MenuClient from '../[slug]/MenuClient';
import type { MenuPageRestaurant } from '../[slug]/MenuClient';

const DEMO_RESTAURANT: MenuPageRestaurant = {
    name: 'Ristorante La Terrazza',
    slug: 'demo',
    description: 'Un viaggio culinario tra i sapori autentici della cucina italiana. Ingredienti freschi, ricette della tradizione e un tocco di creatività chef.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
    themeColor: '#c8a97e',
    backgroundColor: '#fdfaf6',
    textColor: '#2c2c2c',
    fontFamily: 'playfair',
    cardStyle: 'shadow',
    whatsappNumber: '393513487580',
    wineListUrl: null,
    wineList: null,
    champagneList: null,
    drinkList: null,
    googleReviewsUrl: null,
    subscription: {
        plan: 'full',
        hasTranslations: true,
        hasReservations: true,
        status: 'active',
    },
    customLists: [],
    translations: [
        { language: 'en', description: 'A culinary journey through the authentic flavors of Italian cuisine. Fresh ingredients, traditional recipes and a touch of chef creativity.' },
        { language: 'fr', description: 'Un voyage culinaire à travers les saveurs authentiques de la cuisine italienne. Ingrédients frais, recettes traditionnelles et une touche de créativité du chef.' },
        { language: 'de', description: 'Eine kulinarische Reise durch die authentischen Aromen der italienischen Küche. Frische Zutaten, traditionelle Rezepte und ein Hauch Kreativität des Küchenchefs.' },
    ],
    categories: [
        {
            id: 'antipasti',
            name: 'Antipasti',
            translations: [
                { language: 'en', name: 'Starters' },
                { language: 'fr', name: 'Entrées' },
                { language: 'de', name: 'Vorspeisen' },
            ],
            items: [
                {
                    id: 'item-1',
                    name: 'Burrata con Pomodorini e Pesto',
                    description: 'Burrata cremosa di Andria su letto di rucola, accompagnata da pomodorini datterini glassati e pesto di basilico genovese.',
                    price: 14,
                    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7]',
                    translations: [
                        { language: 'en', name: 'Burrata with Cherry Tomatoes & Pesto', description: 'Creamy Andria burrata on a bed of rocket, with glazed cherry tomatoes and Genoese basil pesto.' },
                        { language: 'fr', name: 'Burrata aux Tomates Cerises & Pesto', description: 'Burrata crémeuse d\'Andria sur un lit de roquette, accompagnée de tomates cerises glacées et de pesto de basilic génois.' },
                        { language: 'de', name: 'Burrata mit Kirschtomaten & Pesto', description: 'Cremige Burrata aus Andria auf Rucola-Bett, begleitet von glasierten Kirschtomaten und genueser Basilikumpesto.' },
                    ],
                },
                {
                    id: 'item-2',
                    name: 'Carpaccio di Manzo e Scaglie di Grana',
                    description: 'Sottili fettine di manzo crudo marinato al limone, scaglie di Grana Padano DOP, rucola selvatica e olio EVO.',
                    price: 16,
                    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7]',
                    translations: [
                        { language: 'en', name: 'Beef Carpaccio with Grana Flakes', description: 'Thin slices of lemon-marinated raw beef, Grana Padano DOP flakes, wild rocket and extra virgin olive oil.' },
                        { language: 'fr', name: 'Carpaccio de Bœuf et Copeaux de Grana', description: 'Fines tranches de bœuf cru mariné au citron, copeaux de Grana Padano AOP, roquette sauvage et huile d\'olive vierge extra.' },
                        { language: 'de', name: 'Rindercarpaccio mit Grana-Flocken', description: 'Dünne Scheiben von zitronenmariniertem Rindfleisch, Grana Padano g.U.-Flocken, wilder Rucola und nativem Olivenöl extra.' },
                    ],
                },
            ],
        },
        {
            id: 'primi',
            name: 'Primi Piatti',
            translations: [
                { language: 'en', name: 'First Courses' },
                { language: 'fr', name: 'Premiers Plats' },
                { language: 'de', name: 'Erste Gänge' },
            ],
            items: [
                {
                    id: 'item-3',
                    name: 'Risotto allo Zafferano e Ossobuco',
                    description: 'Il classico milanese: risotto mantecato con zafferano DOP e morbido stufato di ossobuco di vitello. Un abbraccio in un piatto.',
                    price: 22,
                    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7, 12]',
                    translations: [
                        { language: 'en', name: 'Saffron Risotto with Ossobuco', description: 'The Milanese classic: creamy risotto with saffron DOP and tender braised veal ossobuco. A warm hug on a plate.' },
                        { language: 'fr', name: 'Risotto au Safran et Ossobuco', description: 'Le classique milanais : risotto crémeux au safran AOP et tendre ossobuco de veau braisé. Un câlin dans une assiette.' },
                        { language: 'de', name: 'Safranrisotto mit Ossobuco', description: 'Der Mailänder Klassiker: cremiges Risotto mit Safran g.U. und zartem geschmortem Kalbsossobuco. Eine Umarmung auf dem Teller.' },
                    ],
                },
                {
                    id: 'item-4',
                    name: 'Tagliolini al Tartufo Nero',
                    description: 'Pasta fresca all\'uovo tirata a mano, con crema di tartufo nero delle Marche e lamelle di parmigiano 36 mesi.',
                    price: 26,
                    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: false,
                    spiciness: 0,
                    allergens: '[1, 3, 7]',
                    translations: [
                        { language: 'en', name: 'Tagliolini with Black Truffle', description: 'Hand-rolled fresh egg pasta with black truffle cream from Le Marche and 36-month aged parmesan shavings.' },
                        { language: 'fr', name: 'Tagliolini à la Truffe Noire', description: 'Pâtes fraîches aux œufs étalées à la main, avec crème de truffe noire des Marches et lamelles de parmesan affiné 36 mois.' },
                        { language: 'de', name: 'Tagliolini mit schwarzem Trüffel', description: 'Handgezogene frische Eiernudeln mit Schwarztrüffelcreme aus den Marken und 36 Monate gereiftem Parmesan.' },
                    ],
                },
            ],
        },
        {
            id: 'secondi',
            name: 'Secondi Piatti',
            translations: [
                { language: 'en', name: 'Main Courses' },
                { language: 'fr', name: 'Plats Principaux' },
                { language: 'de', name: 'Hauptgänge' },
            ],
            items: [
                {
                    id: 'item-5',
                    name: 'Filetto di Branzino al Vino Bianco',
                    description: 'Branzino selvaggio del Mediterraneo, cotto in crosta di erbe aromatiche con salsa al vino bianco e capperi di Pantelleria.',
                    price: 28,
                    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[4]',
                    translations: [
                        { language: 'en', name: 'Sea Bass Fillet in White Wine', description: 'Wild Mediterranean sea bass, baked in an aromatic herb crust with white wine sauce and Pantelleria capers.' },
                        { language: 'fr', name: 'Filet de Bar au Vin Blanc', description: 'Bar sauvage de Méditerranée, cuit en croûte d\'herbes aromatiques avec sauce au vin blanc et câpres de Pantelleria.' },
                        { language: 'de', name: 'Wolfsbarschfilet in Weißwein', description: 'Wilder Mittelmeer-Wolfsbarsch, in einer Kräuterkruste gebacken mit Weißweinsauce und Pantelleria-Kapern.' },
                    ],
                },
            ],
        },
        {
            id: 'dolci',
            name: 'Dolci',
            translations: [
                { language: 'en', name: 'Desserts' },
                { language: 'fr', name: 'Desserts' },
                { language: 'de', name: 'Desserts' },
            ],
            items: [
                {
                    id: 'item-6',
                    name: 'Tiramisù della Casa',
                    description: 'La nostra versione del classico: savoiardi imbevuti in caffè espresso, crema al mascarpone e cacao amaro di Modica.',
                    price: 9,
                    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: false,
                    spiciness: 0,
                    allergens: '[1, 3, 7]',
                    translations: [
                        { language: 'en', name: 'House Tiramisù', description: 'Our version of the classic: ladyfingers soaked in espresso, mascarpone cream and bitter Modica cocoa.' },
                        { language: 'fr', name: 'Tiramisù Maison', description: 'Notre version du classique : biscuits imbibés d\'expresso, crème au mascarpone et cacao amer de Modica.' },
                        { language: 'de', name: 'Haus-Tiramisù', description: 'Unsere Version des Klassikers: in Espresso getränkte Löffelbiskuits, Mascarponecreme und bitterer Kakao aus Modica.' },
                    ],
                },
            ],
        },
    ],
};

export default function DemoMenuPage() {
    return <MenuClient restaurant={DEMO_RESTAURANT} />;
}
