import MenuClient from '../[slug]/MenuClient';
import type { MenuPageRestaurant } from '../[slug]/MenuClient';

const DEMO_RESTAURANT: MenuPageRestaurant = {
    name: 'Ristorante La Terrazza',
    slug: 'demo',
    description: 'Un viaggio culinario tra i sapori autentici della cucina italiana. Ingredienti freschi, ricette della tradizione e un tocco di creatività chef.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
    themeColor: '#c8a97e',
    backgroundColor: '#fdfaf6',
    textColor: '#2c2c2c',
    fontFamily: 'playfair',
    cardStyle: 'shadow',
    whatsappNumber: '393513487580',
    wineListUrl: null,
    wineList: null,
    champagneList: null,
    drinkList: null,
    googleReviewsUrl: null,
    subscription: {
        plan: 'full',
        hasTranslations: false,
        hasReservations: true,
        status: 'active',
    },
    customLists: [],
    categories: [
        {
            id: 'antipasti',
            name: 'Antipasti',
            translations: [],
            items: [
                {
                    id: 'item-1',
                    name: 'Burrata con Pomodorini e Pesto',
                    description: 'Burrata cremosa di Andria su letto di rucola, accompagnata da pomodorini datterini glassati e pesto di basilico genovese.',
                    price: 14,
                    imageUrl: 'https://images.unsplash.com/photo-1633171580920-f5d2d4c3b5b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7]',
                    translations: [],
                },
                {
                    id: 'item-2',
                    name: 'Carpaccio di Manzo e Scaglie di Grana',
                    description: 'Sottili fettine di manzo crudo marinato al limone, scaglie di Grana Padano DOP, rucola selvatica e olio EVO.',
                    price: 16,
                    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7]',
                    translations: [],
                },
            ],
        },
        {
            id: 'primi',
            name: 'Primi Piatti',
            translations: [],
            items: [
                {
                    id: 'item-3',
                    name: 'Risotto allo Zafferano e Ossobuco',
                    description: 'Il classico milanese: risotto mantecato con zafferano DOP e morbido stufato di ossobuco di vitello. Un abbraccio in un piatto.',
                    price: 22,
                    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[7, 12]',
                    translations: [],
                },
                {
                    id: 'item-4',
                    name: 'Tagliolini al Tartufo Nero',
                    description: 'Pasta fresca all\'uovo tirata a mano, con crema di tartufo nero delle Marche e lamelle di parmigiano 36 mesi.',
                    price: 26,
                    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: false,
                    spiciness: 0,
                    allergens: '[1, 3, 7]',
                    translations: [],
                },
            ],
        },
        {
            id: 'secondi',
            name: 'Secondi Piatti',
            translations: [],
            items: [
                {
                    id: 'item-5',
                    name: 'Filetto di Branzino al Vino Bianco',
                    description: 'Branzino selvaggio del Mediterraneo, cotto in crosta di erbe aromatiche con salsa al vino bianco e capperi di Pantelleria.',
                    price: 28,
                    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: false,
                    isGlutenFree: true,
                    spiciness: 0,
                    allergens: '[4]',
                    translations: [],
                },
            ],
        },
        {
            id: 'dolci',
            name: 'Dolci',
            translations: [],
            items: [
                {
                    id: 'item-6',
                    name: 'Tiramisù della Casa',
                    description: 'La nostra versione del classico: savoiardi imbevuti in caffè espresso, crema al mascarpone e cacao amaro di Modica.',
                    price: 9,
                    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                    isVegan: false,
                    isVegetarian: true,
                    isGlutenFree: false,
                    spiciness: 0,
                    allergens: '[1, 3, 7]',
                    translations: [],
                },
            ],
        },
    ],
};

export default function DemoMenuPage() {
    return <MenuClient restaurant={DEMO_RESTAURANT} />;
}
